name: "Setup PHP"
description: "A composite action to set up PHP with specified version and extensions"

inputs:
  php-version:
    description: "The PHP version to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: ⚙️ Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
      with:
        php-version: ${{ inputs.php-version }}
        extensions: none,iconv,dom,curl,mbstring,tokenizer,xml,xmlwriter,simplexml,ctype
        coverage: pcov

    - name: ♻️ Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: ♻️ Cache composer dependencies
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ inputs.php-versions }}-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: ⚙️ Install dependencies
      shell: bash
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader
        composer --working-dir=tools install --no-progress --prefer-dist --optimize-autoloader
