name: Update CSS Referential

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

permissions: {}

jobs:
  update-css-referential:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: ⚙️ Setup PHP, with composer and extensions
        uses: ./.github/workflows/actions/setup-php
        with:
          php-version: 8.4

      - name: Generate CSS Referential
        run: composer run-script generate-css-referentials

      - name: Push changes and create pull request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          branch: update-css-referential
          add-paths: |
            src/CssLint/Referential
          sign-commits: true
          signoff: true
          title: "feat: update CSS Referential"
          body: |
            This pull request updates the CSS referential files in the `src/CssLint/Referential` directory.
          commit-message: "feat: update CSS Referential"
