name: Update CSS Referential

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-css-referential:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ⚙️ Setup PHP, with composer and extensions
        uses: ./.github/workflows/actions/setup-php
        with:
          php-version: 8.4

      - name: Generate CSS Referential
        run: composer run-script generate-css-referentials

      - name: Push changes and create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          branch: update-css-referential
          add-paths: |
            src/CssLint/Referential
          sign-commits: true
          signoff: true
          title: "feat: update CSS Referential"
          body: |
            This pull request updates the CSS referential files in the `src/CssLint/Referential` directory.
          commit-message: "feat: update CSS Referential"
